# Generated by Django 2.2.10 on 2020-05-28 11:21

import django.contrib.auth.models
from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', pyuploadcare.dj.models.ImageField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', pyuploadcare.dj.models.ImageField(blank=True)),
                ('bio', models.CharField(max_length=255)),
                ('owner', models.CharField(blank=True, max_length=255, verbose_name=django.contrib.auth.models.User)),
            ],
        ),
    ]
